**IMPORT LIABRARIES**
We have to import certain libraries to work with matrices

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/cyberlabs/Linear_train.csv")

In [ ]:
data = np.array(data)
#data = data[:100,:]
print(data.shape)
m , n = data.shape  ## n is the number of features and m is the no. of exapmles
n = n - 2
print(m,n)

(50000, 22)
50000 20


In [ ]:
y = (data[:,n+1:])/100
X = (data[:,1:n+1])/100

print(X.shape,y.shape)

(50000, 20) (50000, 1)


In [ ]:
z = np.ones((m,1))
print(z.shape)

(50000, 1)


In [ ]:
X = np.concatenate((z,X),axis = 1)
print(X.shape)

(50000, 21)


In [ ]:
theta = np.zeros((n+1,1))
print(theta.shape)

(21, 1)


In [ ]:
from os import error
for i in range(100000) :
  cost = []
  h = np.dot(X,theta)
  #print(h.shape)
  error = (h - y)
  delta = (np.dot(X.T,error))/m
  theta = theta - 0.0001*delta
  J = (1/(2*m))*(np.sum(np.multiply(error,error)))
  cost.append(J)
print(J)
print(theta)

230.90387742969273
[[  0.10179593]
 [  7.53193281]
 [  0.16749112]
 [-14.9416791 ]
 [  4.08785808]
 [ 21.28519702]
 [  0.1685332 ]
 [ 10.52936935]
 [-16.39762929]
 [  0.11515916]
 [ 12.63651745]
 [ 17.98510135]
 [  0.59994378]
 [-51.57424917]
 [ 19.06124584]
 [ 25.4578591 ]
 [ 28.6367254 ]
 [ 13.3860048 ]
 [ -0.538627  ]
 [ 53.7385649 ]
 [ 13.84027229]]


In [ ]:
##TESTING
data_test = pd.read_csv("/content/drive/MyDrive/cyberlabs/Linear_test.csv")
data_test = np.array(data_test)

In [ ]:
y_test = (data_test[:,n+1:])/100
X_test = (data_test[:,1:n+1])/100
z_test = np.ones((10000,1))
X_test = np.concatenate((z_test,X_test),axis = 1)
print(y_test.shape)
print(X_test.shape)

(10000, 1)
(10000, 21)


In [ ]:
h_test = np.dot(X_test,theta)
err = h_test - y_test
sq_err = np.sum(err**2)
rmse = np.sqrt(sq_err/10000)
print("RMSE = ",rmse)
print()
print(h_test[:10,:])
print(y_test[:10,:])
J = (1/(2*data_test.shape[0]))*(np.sum(np.multiply(err,err)))
print(J)

RMSE =  21.385119406271443

[[  6.10547044]
 [ 43.19271867]
 [ 20.64315026]
 [-45.1624191 ]
 [ 65.05094944]
 [ 24.72301573]
 [-12.96325431]
 [ 29.7329867 ]
 [ 21.20308353]
 [ 46.13757635]]
[[ -1.63522723]
 [ 64.8466451 ]
 [ 23.93818082]
 [-93.97072355]
 [104.87323575]
 [ 32.56252062]
 [-35.45455997]
 [ 41.02718685]
 [ 27.65424504]
 [ 72.3403361 ]]
228.66166601024375


In [ ]:
##CONCEPT OF RMSE
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,8,3,6,5])
sqr_error = (arr1 - arr2)**2
sqr_error = np.sum(sqr_error)
rmse = np.sqrt(sqr_error/5)
print(rmse)

2.8284271247461903
