**IMPORT LIABRARIES**
We have to import certain libraries to work with matrices

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/cyberlabs/Linear_train.csv")

In [ ]:
data = np.array(data)
#data = data[:100,:]
print(data.shape)
m , n = data.shape  ## n is the number of features and m is the no. of exapmles
n = n - 2
print(m,n)

(50000, 22)
50000 20


In [ ]:
y = (data[:,n+1:])/100
X = (data[:,1:n+1])/100
print(X.shape,y.shape)

(50000, 20) (50000, 1)


In [ ]:
z = np.ones((m,1))
print(z.shape)

(50000, 1)


In [ ]:
X = np.concatenate((z,X),axis = 1)
print(X.shape)

(50000, 21)


In [ ]:
theta = np.zeros((n+1,1))
print(theta.shape)

(21, 1)


In [ ]:
#h = np.dot(X,theta)
#print(h.shape)

In [ ]:
#pred = h - Y
#pred_sq = np.multiply(pred,pred)
#print(pred)
#print(pred.shape)

In [ ]:
#delta = (np.dot(X.T,pred))/m
#print(delta)
#print(delta.shape)

In [ ]:
#theta = np.dot((np.linalg.inv(np.dot(X.T,X))),np.dot((X.T),y))
#print(theta)

In [ ]:
from os import error
for i in range(100000) :
  h = np.dot(X,theta)
  #print(h.shape)
  error = (h - y)
  delta = (np.dot(X.T,error))/m
  theta = theta - 0.0001*delta
  J = (1/(2*m))*(np.sum(np.multiply(error,error)))
print(J)
print(theta)

140.17810264546696
[[  0.11668155]
 [  8.78173026]
 [  0.17440902]
 [-17.53400557]
 [  4.8512623 ]
 [ 24.84789707]
 [  0.16456432]
 [ 12.35326345]
 [-19.18484804]
 [  0.11553766]
 [ 14.84137082]
 [ 20.97182725]
 [  0.59945569]
 [-60.32271598]
 [ 22.32786479]
 [ 29.78158639]
 [ 33.5377823 ]
 [ 15.69137887]
 [ -0.6355825 ]
 [ 62.86685464]
 [ 16.24020676]]


In [ ]:
##TESTING
data_test = pd.read_csv("/content/drive/MyDrive/cyberlabs/Linear_test.csv")
data_test = np.array(data_test)

In [ ]:
y_test = (data_test[:,n+1:])/100
X_test = (data_test[:,1:n+1])/100
z_test = np.ones((10000,1))
X_test = np.concatenate((z_test,X_test),axis = 1)
print(y_test.shape)
print(X_test.shape)

(10000, 1)
(10000, 21)


In [ ]:
h_test = np.dot(X_test,theta)
err = h_test - y_test
print(h_test[:10,:])
print(y_test[:10,:])
J = (1/(2*10000))*(np.sum(np.multiply(err,err)))
print(J)

[[  4.41096723]
 [ 48.04316999]
 [ 21.28212722]
 [-55.88803961]
 [ 73.76018975]
 [ 26.46354904]
 [-17.89595206]
 [ 32.22166895]
 [ 22.52773101]
 [ 51.94339561]]
[[ -1.63522723]
 [ 64.8466451 ]
 [ 23.93818082]
 [-93.97072355]
 [104.87323575]
 [ 32.56252062]
 [-35.45455997]
 [ 41.02718685]
 [ 27.65424504]
 [ 72.3403361 ]]
138.7625907470505
