In [ ]:
##POLYNOMIAL REGRESSSION

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [62]:
data = pd.read_csv("/content/drive/MyDrive/cyberlabs/Polynomial_train.csv")

In [63]:
data = np.array(data)
#data = data[:100,:]
print(data.shape)
m , n = data.shape  ## n is the number of features and m is the no. of exapmles
n = n - 2
print(m,n)

(50000, 5)
50000 3


In [64]:
y = (data[:,n+1:])/100
X = (data[:,1:n+1])/100
print(X.shape,y.shape)

(50000, 3) (50000, 1)


In [65]:
X_sq = np.multiply(X,X)
print(X_sq.shape)

(50000, 3)


In [66]:
X = np.concatenate((X,X_sq),axis = 1)
print(X.shape)


(50000, 6)


In [67]:
z = np.ones((m,1))
print(z.shape)

(50000, 1)


In [68]:
X = np.concatenate((z,X),axis = 1)
print(X.shape)

(50000, 7)


In [69]:
m,n = X.shape
n = n - 1
print(m,n)

50000 6


In [70]:
theta = np.zeros((n+1,1))
print(theta.shape)

(7, 1)


In [72]:
for i in range(100000) :
  h = np.dot(X,theta)
  #print(h.shape)
  er = (h - y)
  delta = (np.dot(X.T,er))/m
  theta = theta - 0.0001*delta
  J = (1/(2*m))*(np.sum(np.multiply(er,er)))
print(J)
print(theta)

72.69655184494718
[[ 0.13252907]
 [ 0.06072182]
 [-0.00256172]
 [ 0.01213549]
 [ 0.0135849 ]
 [-0.04679162]
 [ 0.04082596]]


In [73]:
##TESTING

In [74]:
##TESTING
data_test = pd.read_csv("/content/drive/MyDrive/cyberlabs/Polynomial_test.csv")
data_test = np.array(data_test)
m_train , n_test = data_test.shape
n_test = n_test - 2

In [75]:
y_test = (data_test[:,n_test + 1:])/100
X_test = (data_test[:,1:n_test+1])/100
print(y_test.shape)
print(X_test.shape)

(10000, 1)
(10000, 3)


In [76]:
X_sq_test = np.multiply(X_test,X_test)
print(X_sq_test.shape)

(10000, 3)


In [77]:
X_test = np.concatenate((X_test,X_sq_test),axis = 1)
print(X_test.shape)

(10000, 6)


In [80]:
z = np.ones((m_train,1))
print(z.shape)

(10000, 1)


In [81]:
X_test = np.concatenate((z,X_test),axis = 1)
print(X_test.shape)

(10000, 7)


In [82]:
h_test = np.dot(X_test,theta)
err = h_test - y_test
print(h_test[:10,:])
print(y_test[:10,:])
J = (1/(2*10000))*(np.sum(np.multiply(err,err)))
print(J)

[[0.13916878]
 [0.1348606 ]
 [0.12979052]
 [0.12829545]
 [0.13440223]
 [0.13467289]
 [0.13354535]
 [0.13265094]
 [0.13670454]
 [0.13336377]]
[[ -6.57669309]
 [ -5.45362524]
 [ -0.75044187]
 [-24.03124902]
 [  0.08595325]
 [ 20.35462985]
 [  4.63962554]
 [  0.18406812]
 [ -2.99765366]
 [  1.73285123]]
72.68943907602448
